### ISSUE TITLE
Windows 64 bit dll incorrect

### ISSUE THREAD

**Issue by dscarbro21** [NMGRL/toupcam#14]
Related to the problem in  #5 the dll file in the x64 folder is still incorrect, resulting in an error when loading while running 64 bit Python.

If that file could get updated with the one available at the ToupTek website linked in #5 it could save others from troubleshooting this. Might need to swap out the .lib file too - unsure if that one could be the incorrect version too.

Link for convenience: [http://www.touptek.com/download/showdownload.php?lang=en&id=33](url)

**Comment by noblockhit** [comment]
Sooo, you tell me if i use python 32 bit it should work? imma try that rn!

**Comment by noblockhit** [comment]
Uhm yeah it still doesnt work, but its supposed to with the  BMS110000A right?

**Comment by dscarbro21** [comment]
What I've done is replaced the .lib and the .dll file in the x64 folder with the one I got from the download link above, and everything started working. Could be what's on Git is corrupted, or the .lib file is for 64 but the .dll is for 32 (I don't know much about .lib files, so unsure on that).

Either way, if those files don't get replaced on main, that's the fix.
